remote_theme: huxpro/huxpro.github.io
plugins: [jekyll-paginate]
title: Kirin Security Blog
description: Reaserches, writeups and Cyber Security related articles
# Site settings
title: Kirin Security Blog
SEOTitle: Kirin Security Blog
header-img: img/home-bg.jpg
email: p.dei@kirinsecurity.com
description: "Cyber Security Blog"
keyword: "Cyber Security, Penetration testing, Web Secruity, Red Team"
url: "https://blog.kirinsecurity.com" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username: false
#zhihu_username: false
github_username: DFlavian
twitter_username: z3r0n37
#facebook_username:  huxpro
linkedin_username:  pimen-flavian-dei-296060159

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: z3r0n37

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-4YJZ8HN5GC" # Format: UA-xxxxxx-xx
ga_domain: blog.kirinsecurity.com

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Cyber Security Enthusuast"
sidebar-avatar: https://media-exp1.licdn.com/dms/image/C4E03AQHCYsgHtrX9SA/profile-displayphoto-shrink_200_200/0/1654028726605?e=1670457600&v=beta&t=HZS6n7gHX5zt5EKEv_TIrpji3E-2JDF8I0zFBP4LSFA # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "乱序（Midare）", href: "http://mida.re/" },

  ]
